<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pay\Models\Errors;

class HttpErrorThrowable extends \RuntimeException
{
    public HttpError $container;

    public function __construct(string $message, int $statusCode, HttpError $container)
    {
        parent::__construct($message, $statusCode);
        $this->container = $container;
    }
}