<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pay\Models\Components;


class Availability
{
    /**
     *
     * @var ?Operator $operator
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('operator')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pay\Models\Components\Operator|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Operator $operator = null;

    /**
     *
     * @var ?Operation $operation
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('operation')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pay\Models\Components\Operation|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Operation $operation = null;

    /**
     * @param  ?Operator  $operator
     * @param  ?Operation  $operation
     * @phpstan-pure
     */
    public function __construct(?Operator $operator = null, ?Operation $operation = null)
    {
        $this->operator = $operator;
        $this->operation = $operation;
    }
}