<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pay\Models\Components;


class Operation
{
    /**
     *
     * @var ?Type $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pay\Models\Components\Type|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Type $type = null;

    /**
     *
     * @var ?Status $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pay\Models\Components\Status|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Status $status = null;

    /**
     * @param  ?Type  $type
     * @param  ?Status  $status
     * @phpstan-pure
     */
    public function __construct(?Type $type = null, ?Status $status = null)
    {
        $this->type = $type;
        $this->status = $status;
    }
}