<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pay\Models\Components;


class PaymentRequest
{
    /**
     *
     * @var int $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public int $amount;

    /**
     *
     * @var string $phoneNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phoneNumber')]
    public string $phoneNumber;

    /**
     * @param  int  $amount
     * @param  string  $phoneNumber
     * @phpstan-pure
     */
    public function __construct(int $amount, string $phoneNumber)
    {
        $this->amount = $amount;
        $this->phoneNumber = $phoneNumber;
    }
}