<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pay\Models\Components;


class Payment
{
    /**
     *
     * @var ?int $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $amount = null;

    /**
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     *
     * @var ?string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $currency = null;

    /**
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     *
     * @var ?int $fee
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fee')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $fee = null;

    /**
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     *
     * @var ?int $merchantId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('merchantId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $merchantId = null;

    /**
     *
     * @var ?PaymentType $paymentType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pay\Models\Components\PaymentType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PaymentType $paymentType = null;

    /**
     *
     * @var ?string $phoneNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phoneNumber')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $phoneNumber = null;

    /**
     *
     * @var ?PaymentStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pay\Models\Components\PaymentStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PaymentStatus $status = null;

    /**
     *
     * @var ?TelecomOperator $telecomOperator
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('telecomOperator')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pay\Models\Components\TelecomOperator|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TelecomOperator $telecomOperator = null;

    /**
     *
     * @var ?\DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updatedAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $updatedAt = null;

    /**
     * @param  ?int  $amount
     * @param  ?\DateTime  $createdAt
     * @param  ?string  $currency
     * @param  ?string  $description
     * @param  ?int  $fee
     * @param  ?string  $id
     * @param  ?int  $merchantId
     * @param  ?PaymentType  $paymentType
     * @param  ?string  $phoneNumber
     * @param  ?PaymentStatus  $status
     * @param  ?TelecomOperator  $telecomOperator
     * @param  ?\DateTime  $updatedAt
     * @phpstan-pure
     */
    public function __construct(?int $amount = null, ?\DateTime $createdAt = null, ?string $currency = null, ?string $description = null, ?int $fee = null, ?string $id = null, ?int $merchantId = null, ?PaymentType $paymentType = null, ?string $phoneNumber = null, ?PaymentStatus $status = null, ?TelecomOperator $telecomOperator = null, ?\DateTime $updatedAt = null)
    {
        $this->amount = $amount;
        $this->createdAt = $createdAt;
        $this->currency = $currency;
        $this->description = $description;
        $this->fee = $fee;
        $this->id = $id;
        $this->merchantId = $merchantId;
        $this->paymentType = $paymentType;
        $this->phoneNumber = $phoneNumber;
        $this->status = $status;
        $this->telecomOperator = $telecomOperator;
        $this->updatedAt = $updatedAt;
    }
}