<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pay\Models\Components;

use Pay\Utils\SpeakeasyMetadata;
class Security
{
    /**
     *
     * @var string $apiKeyAuth
     */
    #[SpeakeasyMetadata('security:scheme=true,type=apiKey,subtype=header,name=X-API-Key')]
    public string $apiKeyAuth;

    /**
     * @param  string  $apiKeyAuth
     * @phpstan-pure
     */
    public function __construct(string $apiKeyAuth)
    {
        $this->apiKeyAuth = $apiKeyAuth;
    }
}