<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pay\Models\Components;


enum Status: string
{
    case Operational = 'OPERATIONAL';
    case Suspended = 'SUSPENDED';
}
